### ISSUE TITLE
CIの設定

### ISSUE THREAD

**Issue by albatrosary** [k-mopi/financial-plan#3]
CI は Wercker CI か Circle CI を利用

* [Wercker CI](http://www.wercker.com/)
* [Circle CI](https://circleci.com/)

**Comment by KadoTomohiro** [comment]
travice ciでやってみます

**Comment by KadoTomohiro** [comment]
Wercker CIに変更しました。FTPデプロイ中にエラーで停止しましたがデプロイはできている状態です

**Comment by KadoTomohiro** [comment]
wercker ci
https://app.wercker.com/KadoTomohiro/financial-plan/runs
