### ISSUE TITLE
４つの画面をジェネレートする

### ISSUE THREAD

**Issue by albatrosary** [k-mopi/financial-plan#5]
下記作業を行う：

- [x] 画面のジェネレート
- [x] ルータの設定
- [x] NgModuleを設定しLazy Loadする

**Comment by Naohiro-Hamada** [comment]
#### 画面名
* 収支確認：`incomeConfrimation`
* バランスシート：`balanceSheet`
* ライフイベント：`lifeEvent`
* キャッシュフロー：`cashFlow`

**Comment by albatrosary** [comment]
下記コマンドを使ってください

```
ng generate module --routing true family
```

ひとつ issue が立っていて、update させると routing の設定が入らないようです。

**Comment by albatrosary** [comment]
angular-cli の issue

https://github.com/angular/angular-cli/issues/4614
